### ISSUE TITLE
Server chunked encoder impl out of bounds error

### ISSUE THREAD

**Issue by yoshuawuyts** [http-rs/async-h1#79]
In our chunked encoder impl we try and index outside of the permitted length which causes a panic. We should investigate what is causing this and fix it. First steps towards this were taken in #75 so that our chunked encoding logic is easier to follow. Thanks!

## Todos
- [ ] create a reproducible test case
- [ ] locate the error
- [ ] fix the out of bounds index
